### ISSUE TITLE
[Question]: Is sentry-testkit currently passing tests?

### ISSUE THREAD

**Issue by liamjones** [zivl/sentry-testkit#212]
Hi @zivl,

I'm upgrading our mobile apps from @sentry/react-native from 5.22.2 to 5.35.0. Our tests which use sentry-testkit are currently failing.

I checked out the sentry-testkit project to look into it there first; less code, easier to debug, allows me to work out if the issues are specific to our code.

However, cloning either the head of `master` or the `5.0.9` tag, doing an `npm install` and then `npm run test` immediately results in test failures. Is this expected?

All of the `__tests__/network-interception.test.ts` tests bar one fail like this:

```
  ● sentry test-kit test suite - network interception › performance › should collect child spans

    TypeError: The "stream" argument must be an instance of ReadableStream, WritableStream, or Stream. Received an instance of Socket
```

If they're working for you, what version of node are you on please?

**Comment by liamjones** [comment]
Sorry, I should have dug further. It works on node 16 but not 18+ due, I believe, to this: https://github.com/nock/nock/issues/2466

I'll raise PRs

**Comment by zivl** [comment]
hey @liamjones!

Thanks for reporting this... I actually can reproduce it as well when upgrading to node@18.
`.nvmrc` file points to `node@16`, will you be able to work on 16 until I'll work on something to upgrade it?

**Comment by zivl** [comment]
oh... just saw this: https://github.com/zivl/sentry-testkit/issues/212#issuecomment-2470070430
ok cool :)
and yeah PRs are always welcome 😄
